account/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home, SignUp


app_name = "account"

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('signup', SignUp.as_view(), name='signup'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from dj_rest_auth.registration.views import RegisterView
from allauth.account.views import confirm_email
from users.serializers import UserRegistrationSerializer
from users.views import CustomSignUp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("users.urls")),
    path('users/', include("rest_framework.urls")),
    path('users/dj-rest-auth/', include("dj_rest_auth.urls")),
    path('users/dj-rest-auth/registration/', CustomSignUp.as_view(), name = 'rest_register'),
    path('users/dj-rest-auth/registration/', include("dj_rest_auth.registration.urls")),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home


app_name = "users"

urlpatterns = [
    path('', Home.as_view(), name='home'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy, reverse

class UserManager(BaseUserManager):
    '''User manager with no username but email.'''
    use_in_migrations = True

    def _create_user(self, email, password, role, **kwargs):
        if not email:
            raise ValueError('Email is a required field')
        email = self.normalize_email(email)
        user = self.model(email=email, role=role, **kwargs)
        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_user(self, email, password = None, role=1, **kwargs):
        kwargs.setdefault('is_staff', False)
        kwargs.setdefault('is_superuser', False)
        return self._create_user(email, password, role, **kwargs)
    def create_superuser(self, email, password, role=1, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)

        if kwargs.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if kwargs.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, role, **kwargs)


class User(AbstractUser):
    NORMAL = 3
    ADMIN = 2
    SUPERADMIN = 1
    USER_TYPE = (
        (NORMAL, _('Normal User')),
        (ADMIN, _('Admin User')),
        (SUPERADMIN, _('Super Admin User')),
    )
    role = models.PositiveSmallIntegerField(_('user_type'), choices=USER_TYPE, default=NORMAL)
    username = None
    USERNAME_FIELD = 'email'
    email = models.EmailField(_('email address'), unique=True)
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self) -> str:
        return self.email

account/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect

from rest_framework.generics import CreateAPIView
from rest_framework import permissions

from .models import User
from .serializers import UserRegistrationSerializer


class Home(TemplateView):
    template_name = "account/home.html"

class SignUp(CreateAPIView):
    model = get_user_model()
    permission_classes = [
        permissions.AllowAny
    ]
    serializer_class = UserRegistrationSerializer
    queryset = User.objects.all()
    
    # def create(self, request, *args, **kwargs):
    #     return super().create(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request=request, template_name='account/signup.html')

    def post(self, request, *args, **kwargs):
        user = self.create(request, *args, **kwargs)
        return HttpResponseRedirect(reverse('login'))

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect

from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework import permissions
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from dj_rest_auth.registration.views import RegisterView

from .models import User
from .serializers import UserRegistrationSerializer, UserLoginSerializer, UserSerializer


class Home(ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CustomSignUp(RegisterView):
    serializer_class = UserRegistrationSerializer

    def get_serializer_class(self):
        return UserRegistrationSerializer

users/templates/users/home.html
<h1>Home</h1>

User = {{ user }}<br>


{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a><br>
{% else %}
    <a href="{% url 'users:signup' %}">New User</a>
    <a href="{% url 'login' %}">Login</a>
{% endif %}

users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

{% load rest_framework %}
<form method="POST" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <!-- <div class="mb-3">
        <label class="form-label" for="inputEmail">Email</label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="mb-3">
        <label class="form-label" for="inputPassword">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <label>Role</label>
    <select name="role" id="role">
        <option value=3>Normal</option>
        <option value=1>Super Admin</option>
        <option value=2>Admin</option>
    </select> -->
    {% render_form serializer %}
    <button type="submit" class="btn btn-primary">Sign in</button>
</form>